### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Exelord** [vihryn/ember-rollbar#14]
Hi :)
Do you plan to continue maintenance of this project? It needs a little bit o love... some upgrades, more options, better handling etc.

**Comment by vvscode** [comment]
@Exelord  what certainly do you want?

**Comment by vihryn** [comment]
hi :)

**Comment by Exelord** [comment]
The project needs:
### Rutin Maintenance:
- Rollbar update
- upgrade of CLI
- packages update

### Improvements and features
- remove all bower dependencies in favor of node modules
- improve rollbar service to be a fully fledge wrapper (not just a layer)
- support for Fastboot
- support for uploading source maps

### Notes
`Ember.Logger` is an internal object. You should handle errors from:
- `Ember.onerror` - Handling errors from `Ember.assert`
- `window.onerror` (not sure about that) -  Handling errors from pure JS
- `Ember.RSVP.on('error')` (alternatively `errors` form `ajax`) - Handling errors from requests
- [WarnHandler](https://www.emberjs.com/api/classes/Ember.Debug.html#method_registerWarnHandler) - Handling errors from `Ember.warn`
- [DeprecationHandler](https://www.emberjs.com/api/classes/Ember.Debug.html#method_registerDeprecationHandler) - Handling errors from `Ember.deprecate`

___
I was working on that kind of package for my projects (I have about 80% completed) then I found your which is not so bad for my needs just require a little polish :)

I'm wondering if you intend to maintain and support this package in the direction I wrote higher or I should create my own.

We can also work together on that if you are interested :) I'm also open for takeover in a case when you do not plan to continue work on the package.
