### ISSUE TITLE
accessToken

### ISSUE THREAD

**Issue by Dragsbaek** [vihryn/ember-rollbar#9]
Hey, thanks for sharing. I dont see any documentation about how/where to add the accessToken?

**Comment by vvscode** [comment]
@Dragsbaek  Inside you APP settings (`config/environment.js`) define key `ROLLBAR_KEY`

```javascript
module.exports = function(environment) {
  var ENV = {
     // ...
    APP: {
        // ....
        ROLLBAR_ENABLED: false,
        ROLLBAR_ENV: "dev",
        ROLLBAR_KEY: "",
```

**Comment by vvscode** [comment]
Like here https://github.com/vihryn/ember-rollbar/pull/10/files?w=1
